### ISSUE TITLE
Max retries exceeded with url ってエラー

### ISSUE THREAD

**Issue by kentoku24** [kentoku24/desknetsNotifier#17]
title:新商品チームMTG, start_time:2018-02-13 18:00:00, end_time:2018-02-13 19:00:00, location:18-1 【18-2】会議室（12名
）
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 294, in connect
    self._tunnel()
  File "C:\Python36\lib\http\client.py", line 919, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authorization Required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/
reminders.list (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authoriza
tion Required.',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jmottoScraper.py", line 192, in <module>
    token=SLACK_TOKEN
  File "C:\Python36\lib\site-packages\slackclient\client.py", line 85, in api_call
    result = json.loads(self.server.api_call(method, timeout=timeout, **kwargs))
  File "C:\Python36\lib\site-packages\slackclient\server.py", line 251, in api_call
    return self.api_requester.do(self.token, method, kwargs, timeout=timeout).text
  File "C:\Python36\lib\site-packages\slackclient\slackrequest.py", line 85, in do
    proxies=self.proxies)
  File "C:\Python36\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/re
minders.list (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authorizati
on Required.',)))

**Comment by kentoku24** [comment]
たぶんMenloのせい
